local Config = DDHunting.Config

Config.Contracts = {
    MaxActivePerPlayer = 4,
    RefreshIntervalMinutes = 45,
    BoardRefreshCooldownSeconds = 90,
    DefaultDurationMinutes = 120,

    Boards = {
        ranger = {
            label = 'Ranger Board',
            contractTypes = { 'legal_hunt', 'predator_control' },
            allowIllegal = false,
            payoutAccount = 'money',
        },
        trapper = {
            label = 'Trapper Board',
            contractTypes = { 'trapper_material' },
            allowIllegal = false,
            payoutAccount = 'money',
        },
        trophy = {
            label = 'Trophy Board',
            contractTypes = { 'trophy_collector' },
            allowIllegal = false,
            payoutAccount = 'money',
        },
        black_market = {
            label = 'Black Market Board',
            contractTypes = { 'black_market' },
            allowIllegal = true,
            payoutAccount = 'black_money',
        },
    },

    DifficultyTiers = {
        t1 = { weight = 55, payoutMult = 1.00, xpMult = 1.00, repMult = 1.00, maxFreshnessDecayPenalty = 0.10 },
        t2 = { weight = 30, payoutMult = 1.35, xpMult = 1.30, repMult = 1.22, maxFreshnessDecayPenalty = 0.15 },
        t3 = { weight = 12, payoutMult = 1.80, xpMult = 1.65, repMult = 1.50, maxFreshnessDecayPenalty = 0.20 },
        t4 = { weight = 3, payoutMult = 2.55, xpMult = 2.10, repMult = 1.90, maxFreshnessDecayPenalty = 0.25 },
    },

    TypePools = {
        legal_hunt = {
            label = 'Legal Harvest Supply',
            itemPool = { 'raw_meat', 'animal_pelt', 'animal_part' },
            legalRequired = true,
            speciesPool = { 'rabbit', 'deer', 'boar' },
            quantity = { min = 3, max = 12 },
            freshness = { min = 50, max = 90 },
            quality = { min = 45, max = 80 },
            variant = { 'normal', 'rare' },
            timeLimitMinutes = { min = 60, max = 150 },
            basePayout = 750,
            baseXP = 90,
            repType = 'legal',
            baseRep = 10,
        },
        trapper_material = {
            label = 'Trapper Material Order',
            itemPool = { 'animal_pelt', 'salted_pelt', 'treated_pelt', 'animal_part' },
            legalRequired = true,
            speciesPool = { 'deer', 'boar' },
            partTypePool = { 'antlers', 'tusk', 'fang', 'claw' },
            quantity = { min = 2, max = 8 },
            quality = { min = 55, max = 88 },
            freshness = { min = 30, max = 75 },
            timeLimitMinutes = { min = 80, max = 180 },
            basePayout = 920,
            baseXP = 105,
            repType = 'trapper',
            baseRep = 12,
        },
        trophy_collector = {
            label = 'Trophy Collector Commission',
            itemPool = { 'animal_trophy', 'mounted_trophy' },
            legalRequired = true,
            speciesPool = { 'deer', 'boar' },
            quantity = { min = 1, max = 3 },
            trophyScore = { min = 80, max = 210 },
            quality = { min = 70, max = 95 },
            variant = { 'normal', 'rare', 'albino', 'melanistic' },
            timeLimitMinutes = { min = 120, max = 240 },
            basePayout = 1550,
            baseXP = 165,
            repType = 'trophy',
            baseRep = 17,
        },
        black_market = {
            label = 'Black Market Contraband Run',
            itemPool = { 'contraband_meat', 'protected_pelt', 'falsified_tag', 'wildlife_evidence' },
            legalRequired = false,
            speciesPool = { 'deer', 'boar' },
            quantity = { min = 2, max = 10 },
            freshness = { min = 20, max = 80 },
            quality = { min = 30, max = 90 },
            timeLimitMinutes = { min = 45, max = 130 },
            basePayout = 1700,
            baseXP = 140,
            repType = 'black_market',
            baseRep = 15,
            heatDeltaOnComplete = 8,
        },
        predator_control = {
            label = 'Predator Control Assignment',
            itemPool = { 'animal_part', 'animal_pelt' },
            legalRequired = true,
            speciesPool = { 'wolf', 'coyote', 'mountain_lion', 'bear' },
            partTypePool = { 'fang', 'claw' },
            quantity = { min = 1, max = 5 },
            quality = { min = 50, max = 85 },
            freshness = { min = 40, max = 85 },
            timeLimitMinutes = { min = 75, max = 170 },
            basePayout = 1380,
            baseXP = 130,
            repType = 'legal',
            baseRep = 14,
        },
    },
}
